version: "3.9"

services:
  language-ui:
    build: ./language-ui
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - audio-services

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  audio-services:
    build: ./audio-services
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: XcYrNNwJ0SbxazMJT2HkCDaNg9yqAPqBtCTRtbeyM2o=
      MINIO_URL: http://minio:9000
    depends_on:
      - minio
      - auth-service

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

volumes:
  minio-data:
